on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#   - run: wget https://download.java.net/openjdk/jdk21/ri/openjdk-21+35_linux-x64_bin.tar.gz
#   - uses: actions/setup-java@v4
#     with:
#       distribution: 'jdkfile'
#       jdkFile: openjdk-21+35_linux-x64_bin.tar.gz
#       java-version: 21
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 23
    - uses: actions/checkout@v4
#   - run: sudo apt install libjinput-java libxcursor-dev libxrandr-dev libxxf86vm-dev
    - run: ant jars
    - uses: actions/upload-artifact@v4
      with:
        path: |
          libs/lwjgl.jar
          libs/lwjgl_util_applet.jar
          libs/lwjgl_test.jar
          libs/lwjgl_util.jar
        compression-level: 9
#   - uses: actions/upload-artifact@v1
#     with:
#       name: lwjgl-2.9.4.zip
#       path: dist/lwjgl-2.9.4.zip
#   - uses: softprops/action-gh-release@v1
#     if: startsWith(github.ref, 'refs/tags/')
#     with:
#       files: dist/lwjgl-2.9.4.zip
#       tag_name:  ${{ github.ref }}
#       name: Release ${{ github.ref }}
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
